import { streetLessonsFor } from "@/lib/game/street-task-lessons";
import type { DistrictTaskPack } from "./tasks";

const charminarLane: DistrictTaskPack = {
  districtId: "charminar-lane",
  finale: {
    title: "CHARMINAR MORNING DONE",
    text: "Auto to Secunderabad, mirchi bajji, Charminar flowers, bus to Golconda — Hyderabad in Telugu.",
  },
  tasks: [
    {
      id: "charminar-lane-auto",
      districtId: "charminar-lane",
      kind: "auto",
      pos: [20, -4],
      title: "Auto to Secunderabad",
      brief: "Hail the auto to Secunderabad station and agree a fair fare under ₹150.",
      reward: 250,
      interactLabel: "Hail the auto",
      name: "Venkat",
      role: "Auto Driver",
      speaker: "vijay",
      colour: 0xf5c518,
      completionNote: "Fare settled — Secunderabad station bound.",
      lessons: streetLessonsFor("charminar-lane-auto"),
    },
    {
      id: "charminar-lane-shop",
      districtId: "charminar-lane",
      kind: "shop",
      pos: [-18, 7],
      title: "Mirchi bajji",
      brief: "Order mirchi bajjis and tea at the lane stall.",
      reward: 180,
      interactLabel: "Order at the stall",
      name: "Lakshmi",
      role: "Bajji Seller",
      speaker: "neha",
      colour: 0xe74c3c,
      completionNote: "Mirchi bajji and tea — old city snack.",
      lessons: streetLessonsFor("charminar-lane-shop"),
    },
    {
      id: "charminar-lane-temple",
      districtId: "charminar-lane",
      kind: "temple",
      pos: [8, 20],
      title: "Flowers at Charminar",
      brief: "Buy marigold garlands near Charminar. Ask the price before you pay.",
      reward: 200,
      interactLabel: "Buy flowers",
      name: "Rahim",
      role: "Flower Seller",
      speaker: "ritu",
      colour: 0x8e44ad,
      completionNote: "Garlands in hand — ready for darshan.",
      lessons: streetLessonsFor("charminar-lane-temple"),
    },
    {
      id: "charminar-lane-bus",
      districtId: "charminar-lane",
      kind: "bus",
      pos: [-6, -22],
      title: "Bus to Golconda",
      brief: "Buy a ticket to Golconda. Name the stop and ask the fare.",
      reward: 220,
      interactLabel: "Buy bus ticket",
      name: "Srinivas",
      role: "Conductor",
      speaker: "shubh",
      colour: 0x2980b9,
      completionNote: "Ticket to Golconda — keep it for checking.",
      lessons: streetLessonsFor("charminar-lane-bus"),
    },
  ],
};

const fortKochi: DistrictTaskPack = {
  districtId: "fort-kochi",
  finale: {
    title: "FORT KOCHI ERRANDS DONE",
    text: "Auto to Ernakulam, puttu breakfast, church flowers, bus to Fort Kochi — Kerala in Malayalam.",
  },
  tasks: [
    {
      id: "fort-kochi-auto",
      districtId: "fort-kochi",
      kind: "auto",
      pos: [20, -4],
      title: "Auto to Ernakulam",
      brief: "Negotiate with the auto to Ernakulam South and agree on ₹150.",
      reward: 250,
      interactLabel: "Hail the auto",
      name: "Unni",
      role: "Auto Driver",
      speaker: "vijay",
      colour: 0xf5c518,
      completionNote: "Auto to Ernakulam South — fare settled.",
      lessons: streetLessonsFor("fort-kochi-auto"),
    },
    {
      id: "fort-kochi-shop",
      districtId: "fort-kochi",
      kind: "shop",
      pos: [-18, 7],
      title: "Puttu and chai",
      brief: "Order puttu and chai at the waterfront stall.",
      reward: 180,
      interactLabel: "Order at the stall",
      name: "Mary",
      role: "Puttu Stall",
      speaker: "rohan",
      colour: 0x16a085,
      completionNote: "Puttu and chai — Kochi morning.",
      lessons: streetLessonsFor("fort-kochi-shop"),
    },
    {
      id: "fort-kochi-temple",
      districtId: "fort-kochi",
      kind: "temple",
      pos: [8, 20],
      title: "Church flowers",
      brief: "Buy garlands for the church stall before the bell.",
      reward: 200,
      interactLabel: "Buy flowers",
      name: "Thomas",
      role: "Flower Stall",
      speaker: "kavitha",
      colour: 0x8e44ad,
      completionNote: "Garlands ready — bell is ringing.",
      lessons: streetLessonsFor("fort-kochi-temple"),
    },
    {
      id: "fort-kochi-bus",
      districtId: "fort-kochi",
      kind: "bus",
      pos: [-6, -22],
      title: "Bus to Fort Kochi",
      brief: "Get a ticket to Fort Kochi on the city bus.",
      reward: 220,
      interactLabel: "Buy bus ticket",
      name: "Varghese",
      role: "Conductor",
      speaker: "shubh",
      colour: 0x2980b9,
      completionNote: "Ticket to Fort Kochi — board from the back.",
      lessons: streetLessonsFor("fort-kochi-bus"),
    },
  ],
};

const dadarChowk: DistrictTaskPack = {
  districtId: "dadar-chowk",
  finale: {
    title: "DADAR ERRANDS DONE",
    text: "Auto to Dadar station, vada pav, Siddhivinayak flowers, bus to Bandra — Mumbai in Marathi.",
  },
  tasks: [
    {
      id: "dadar-chowk-auto",
      districtId: "dadar-chowk",
      kind: "auto",
      pos: [20, -4],
      title: "Auto to Dadar station",
      brief: "Hail the auto to Dadar railway station and settle the fare.",
      reward: 250,
      interactLabel: "Stop the auto",
      name: "Nitin",
      role: "Auto Driver",
      speaker: "vijay",
      colour: 0xf5c518,
      completionNote: "Dadar station — fare agreed in Marathi.",
      lessons: streetLessonsFor("dadar-chowk-auto"),
    },
    {
      id: "dadar-chowk-shop",
      districtId: "dadar-chowk",
      kind: "shop",
      pos: [-18, 7],
      title: "Vada pav",
      brief: "Order vada pav and cutting chai at the chowk stall.",
      reward: 180,
      interactLabel: "Order vada pav",
      name: "Sandeep",
      role: "Vada Pav Stall",
      speaker: "rohan",
      colour: 0xe67e22,
      completionNote: "Vada pav and cutting — classic Dadar.",
      lessons: streetLessonsFor("dadar-chowk-shop"),
    },
    {
      id: "dadar-chowk-temple",
      districtId: "dadar-chowk",
      kind: "temple",
      pos: [8, 20],
      title: "Siddhivinayak flowers",
      brief: "Buy marigold garlands for Siddhivinayak before the bell.",
      reward: 200,
      interactLabel: "Buy flowers",
      name: "Usha",
      role: "Flower Seller",
      speaker: "ritu",
      colour: 0xe74c3c,
      completionNote: "Garlands for darshan — hurry, bell ringing.",
      lessons: streetLessonsFor("dadar-chowk-temple"),
    },
    {
      id: "dadar-chowk-bus",
      districtId: "dadar-chowk",
      kind: "bus",
      pos: [-6, -22],
      title: "Bus to Bandra",
      brief: "Buy a BEST ticket to Bandra at the chowk stop.",
      reward: 220,
      interactLabel: "Buy bus ticket",
      name: "Rajesh",
      role: "Conductor",
      speaker: "gokul",
      colour: 0x5d6d7e,
      completionNote: "Ticket to Bandra — keep it for checking.",
      lessons: streetLessonsFor("dadar-chowk-bus"),
    },
  ],
};

const manekChowk: DistrictTaskPack = {
  districtId: "manek-chowk",
  finale: {
    title: "MANEK CHOWK DONE",
    text: "Auto to Kalupur, fafda-jalebi, temple flowers, bus to Law Garden — Ahmedabad in Gujarati.",
  },
  tasks: [
    {
      id: "manek-chowk-auto",
      districtId: "manek-chowk",
      kind: "auto",
      pos: [20, -4],
      title: "Auto to Kalupur",
      brief: "Negotiate the auto to Kalupur railway station under ₹150.",
      reward: 250,
      interactLabel: "Hail the auto",
      name: "Jayesh",
      role: "Auto Driver",
      speaker: "vijay",
      colour: 0xf5c518,
      completionNote: "Kalupur station — fare settled.",
      lessons: streetLessonsFor("manek-chowk-auto"),
    },
    {
      id: "manek-chowk-shop",
      districtId: "manek-chowk",
      kind: "shop",
      pos: [-18, 7],
      title: "Fafda and jalebi",
      brief: "Order fafda, jalebi, and chaas at the chowk stall.",
      reward: 180,
      interactLabel: "Order snacks",
      name: "Kiran",
      role: "Fafda Stall",
      speaker: "shruti",
      colour: 0xf39c12,
      completionNote: "Fafda-jalebi breakfast — Manek classic.",
      lessons: streetLessonsFor("manek-chowk-shop"),
    },
    {
      id: "manek-chowk-temple",
      districtId: "manek-chowk",
      kind: "temple",
      pos: [8, 20],
      title: "Temple flowers",
      brief: "Buy marigold garlands at the temple gate.",
      reward: 200,
      interactLabel: "Buy flowers",
      name: "Daxa",
      role: "Flower Seller",
      speaker: "ritu",
      colour: 0xe74c3c,
      completionNote: "Mala for darshan — bell is ringing.",
      lessons: streetLessonsFor("manek-chowk-temple"),
    },
    {
      id: "manek-chowk-bus",
      districtId: "manek-chowk",
      kind: "bus",
      pos: [-6, -22],
      title: "Bus to Law Garden",
      brief: "Buy a city bus ticket to Law Garden.",
      reward: 220,
      interactLabel: "Buy bus ticket",
      name: "Harsh",
      role: "Conductor",
      speaker: "shubh",
      colour: 0x27ae60,
      completionNote: "Ticket to Law Garden — board from the back.",
      lessons: streetLessonsFor("manek-chowk-bus"),
    },
  ],
};

const hallBazaar: DistrictTaskPack = {
  districtId: "hall-bazaar",
  finale: {
    title: "HALL BAZAAR DONE",
    text: "Auto to the Golden Temple, lassi, karah prasad, bus to Hall Bazaar — Amritsar in Punjabi.",
  },
  tasks: [
    {
      id: "hall-bazaar-auto",
      districtId: "hall-bazaar",
      kind: "auto",
      pos: [20, -4],
      title: "Auto to Harmandir Sahib",
      brief: "Hail the auto to Sri Harmandir Sahib and agree the fare.",
      reward: 250,
      interactLabel: "Hail the auto",
      name: "Jasbir",
      role: "Auto Driver",
      speaker: "vijay",
      colour: 0xf5c518,
      completionNote: "Golden Temple bound — fare settled.",
      lessons: streetLessonsFor("hall-bazaar-auto"),
    },
    {
      id: "hall-bazaar-shop",
      districtId: "hall-bazaar",
      kind: "shop",
      pos: [-18, 7],
      title: "Lassi at the bazaar",
      brief: "Order sweet lassi and tea at the bazaar stall.",
      reward: 180,
      interactLabel: "Order lassi",
      name: "Navjot",
      role: "Lassi Stall",
      speaker: "rohan",
      colour: 0xf39c12,
      completionNote: "Meethi lassi — Amritsar cool-down.",
      lessons: streetLessonsFor("hall-bazaar-shop"),
    },
    {
      id: "hall-bazaar-temple",
      districtId: "hall-bazaar",
      kind: "temple",
      pos: [8, 20],
      title: "Karah prasad",
      brief: "Buy karah prasad before sangat arrives.",
      reward: 200,
      interactLabel: "Buy prasad",
      name: "Manpreet",
      role: "Prasad Stall",
      speaker: "kavitha",
      colour: 0x8e44ad,
      completionNote: "Karah prasad in hand — join the queue.",
      lessons: streetLessonsFor("hall-bazaar-temple"),
    },
    {
      id: "hall-bazaar-bus",
      districtId: "hall-bazaar",
      kind: "bus",
      pos: [-6, -22],
      title: "Bus to Hall Bazaar",
      brief: "Buy a ticket to Hall Bazaar at the stop.",
      reward: 220,
      interactLabel: "Buy bus ticket",
      name: "Gurinder",
      role: "Conductor",
      speaker: "shubh",
      colour: 0x2980b9,
      completionNote: "Ticket to Hall Bazaar — keep it handy.",
      lessons: streetLessonsFor("hall-bazaar-bus"),
    },
  ],
};

const lingarajLane: DistrictTaskPack = {
  districtId: "lingaraj-lane",
  finale: {
    title: "LINGARAJ LANE DONE",
    text: "Auto to Master Canteen, pakhala, Lingaraj flowers, bus to KIIT square — Bhubaneswar in Odia.",
  },
  tasks: [
    {
      id: "lingaraj-lane-auto",
      districtId: "lingaraj-lane",
      kind: "auto",
      pos: [20, -4],
      title: "Auto to Master Canteen",
      brief: "Negotiate the auto to Master Canteen and agree on ₹150.",
      reward: 250,
      interactLabel: "Hail the auto",
      name: "Santosh",
      role: "Auto Driver",
      speaker: "vijay",
      colour: 0xf5c518,
      completionNote: "Master Canteen — fare settled in Odia.",
      lessons: streetLessonsFor("lingaraj-lane-auto"),
    },
    {
      id: "lingaraj-lane-shop",
      districtId: "lingaraj-lane",
      kind: "shop",
      pos: [-18, 7],
      title: "Pakhala plate",
      brief: "Order a plate of pakhala with badi chutney.",
      reward: 180,
      interactLabel: "Order pakhala",
      name: "Sabita",
      role: "Pakhala Stall",
      speaker: "ishita",
      colour: 0x16a085,
      completionNote: "Pakhala and badi — Odia lunch.",
      lessons: streetLessonsFor("lingaraj-lane-shop"),
    },
    {
      id: "lingaraj-lane-temple",
      districtId: "lingaraj-lane",
      kind: "temple",
      pos: [8, 20],
      title: "Lingaraj flowers",
      brief: "Buy marigold garlands for Lingaraj before arati.",
      reward: 200,
      interactLabel: "Buy flowers",
      name: "Debasish",
      role: "Flower Seller",
      speaker: "ritu",
      colour: 0xe74c3c,
      completionNote: "Maala ready — bell is ringing.",
      lessons: streetLessonsFor("lingaraj-lane-temple"),
    },
    {
      id: "lingaraj-lane-bus",
      districtId: "lingaraj-lane",
      kind: "bus",
      pos: [-6, -22],
      title: "Bus to KIIT square",
      brief: "Buy a city bus ticket to KIIT square.",
      reward: 220,
      interactLabel: "Buy bus ticket",
      name: "Pradeep",
      role: "Conductor",
      speaker: "soham",
      colour: 0x5d6d7e,
      completionNote: "Ticket to KIIT square — board from the back.",
      lessons: streetLessonsFor("lingaraj-lane-bus"),
    },
  ],
};

export const SIX_SEED_TASK_PACKS: DistrictTaskPack[] = [
  charminarLane,
  fortKochi,
  dadarChowk,
  manekChowk,
  hallBazaar,
  lingarajLane,
];
