/**
 * Ordered (Bayer) dithering.
 *
 * Every procedural surface in this project is generated as float fields and
 * then written into an 8-bit canvas. Rounding a smooth float ramp to 256
 * levels is exactly the situation that produces *banding* — the flat stair-step
 * contours you see across plaster walls, asphalt and the sky gradient. A
 * per-pixel ordered threshold breaks the quantisation error up into a fine
 * regular pattern that the eye integrates back into a smooth ramp, at zero
 * runtime cost (it happens once, at texture bake time).
 *
 * The same 8x8 matrix is exported as GLSL so the post-processing grade pass can
 * dither the *final frame* too: bloom, haze and the sky sphere all produce
 * near-flat low-contrast gradients across hundreds of pixels, which band on an
 * 8-bit display no matter how clean the texture behind them is.
 */

/** Edge length of the Bayer matrix. */
export const BAYER_N = 8;

/**
 * Canonical 8x8 Bayer matrix, generated by the recursive doubling rule
 *   M(2n) = [ 4M(n)+0  4M(n)+2 ;  4M(n)+3  4M(n)+1 ]
 * rather than pasted in as a magic table.
 */
function buildBayer(n: number): Int32Array {
  let m = Int32Array.of(0);
  let size = 1;
  while (size < n) {
    const next = new Int32Array(size * size * 4);
    const w = size * 2;
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const v = m[y * size + x] * 4;
        next[y * w + x] = v;
        next[y * w + (x + size)] = v + 2;
        next[(y + size) * w + x] = v + 3;
        next[(y + size) * w + (x + size)] = v + 1;
      }
    }
    m = next;
    size = w;
  }
  return m;
}

const BAYER = buildBayer(BAYER_N);

/**
 * Threshold for pixel (x, y), in [0, 1). Wraps, so it is safe to call with
 * unbounded coordinates.
 */
export function bayer(x: number, y: number): number {
  const xi = x & (BAYER_N - 1);
  const yi = y & (BAYER_N - 1);
  return (BAYER[yi * BAYER_N + xi] + 0.5) / (BAYER_N * BAYER_N);
}

/**
 * Quantise a [0,1] value to an 8-bit channel with ordered dithering.
 *
 * `amount` is measured in output levels: 1.0 spreads the error across exactly
 * one 8-bit step, which is the amount that removes banding without adding
 * visible noise. Push it higher only for very low-contrast ramps.
 */
export function ditherByte(v: number, x: number, y: number, amount = 1): number {
  const t = (bayer(x, y) - 0.5) * amount;
  const q = Math.round(v * 255 + t);
  return q < 0 ? 0 : q > 255 ? 255 : q;
}

/**
 * GLSL implementation of the same matrix, for screen-space dithering in a
 * post pass. Declares `float bayer8(vec2 p)` returning [0,1).
 *
 * A texture lookup would need a sampler binding and an upload for 64 bytes of
 * data; the closed form below is a handful of ALU ops and no extra bindings,
 * which matters because it runs on every pixel of every frame. `bayer2` is the
 * 2x2 base matrix ([[0,2],[3,1]]/4) written as one fract(), and each larger
 * matrix is the recursive doubling rule expressed as a scaled sum.
 */
export const BAYER_GLSL = /* glsl */ `
  float bayer2(vec2 a) {
    a = floor(a);
    return fract(a.x * 0.5 + a.y * a.y * 0.75);
  }
  float bayer4(vec2 a) { return bayer2(0.5 * a) * 0.25 + bayer2(a); }
  float bayer8(vec2 a) { return bayer4(0.5 * a) * 0.25 + bayer2(a); }
`;
